### ISSUE TITLE
Line through highlight colour of various sections of the Plasma theme. 

### ISSUE THREAD

**Issue by linusrg1** [HimDek/Utterly-Round-Plasma-Style#1]
![Screenshot_20221015_185202](https://user-images.githubusercontent.com/67347319/196011004-81d7aedb-0070-4d3a-8c4c-41e76d812ada.jpg)
As you can see there is a line going through the centre of the search bar highlight here. The same thing happens with menu highlights as well. 

Software info: 
Operating System: openSUSE Tumbleweed 20221014
KDE Plasma Version: 5.26.0
KDE Frameworks Version: 5.99.0
Qt Version: 5.15.6
Kernel Version: 6.0.1-1-default (64-bit)
Graphics Platform: Wayland

**Comment by HimDek** [comment]
Whats you screen resolution?

**Comment by linusrg1** [comment]
my screen resolution is 1280x800

**Comment by kalkishnu** [comment]
I can see the same line, and i get it also on the text input of the kde locker screen. My resolution is 1920x1080.

**Comment by HimDek** [comment]
Fixed for  search bar with https://github.com/HimDek/Utterly-Round-Plasma-Style/commit/9883254d1f20edc27cc8f7f5620e8ba828fd2624

If its happening for any other elements, please share a screenshot and reopen this issue
