### ISSUE TITLE
Utterly Nord window decoration is pixelated on Plasma 6 with Wayland

### ISSUE THREAD

**Issue by v1rtl** [HimDek/Utterly-Round-Plasma-Style#11]
This happens for both Solid and Blur versions

![image](https://github.com/HimDek/Utterly-Nord-Plasma/assets/35937217/cefbf0fd-1197-423a-8956-5c14bda8af78)
![image](https://github.com/HimDek/Utterly-Nord-Plasma/assets/35937217/8201d898-3399-4f54-b374-7f78f16b381b)

Both window decorations were previously uninstalled and then re-installed from KDE Store

button size is set to "Tiny". Changing scaling doesn't have any effect

**Comment by v1rtl** [comment]
on X11 they're like this:

![image](https://github.com/HimDek/Utterly-Nord-Plasma/assets/35937217/e0063400-4580-4a58-bb43-16ba05693fef)

**Comment by HimDek** [comment]
Transfered to [Utterly-Round-Plasma-Style](https://github.com/HimDek/Utterly-Round-Plasma-Style/issues/11) as all Utterly themes use Utterly Round Window Decorations which is a part of Utterly-Round-Plasma-Style

**Comment by v1rtl** [comment]
why was this closed? the issue is still prevalent
